### ISSUE TITLE
Cannot Login.

### ISSUE THREAD

**Issue by amitiyer** [goautodial/v4.0#1]
Hello, 

I have installed Goautodial 3.3v and then changed the web files to v4.0 and changed the 3 files that are mentioned but now i cannot login, i have set the database credentials of root mysql user. Secondly, I have also manually installed asterisk and dahdi with vicidial and then replaced the http with v4.0 and still i got the same issue, Can you please let us know how is the correct way to install this on Centos or any other operating System ?

**Comment by demianb** [comment]
We'll be posting the instructions on how to upgrade to version 4 soon. It's not as straightforward as overwriting the files in the HTML folder and modifying the .conf files. There are some prerequisites software like Kamailio SIP server (for webRTC), DNSmasq (if you don't have a local DNS server), Asterisk 13, OSticket database and etc.

**Comment by demianb** [comment]
Please keep in mind that this is not an official release yet nor beta or RC.

**Comment by amitiyer** [comment]
Hello @demianb ,

I understand it is not any official release or beta. Can you please let us know when will the instructions be updated in the wiki ?

**Comment by brett005** [comment]
i have the same thing with all step login not working same for agent and same for admin

they are a fil named install.php i have run it too after i have rename install.txt to samething other then this one they are add same table in goautodial database as i have notice.
finaly always login not working hope we find same help and same way

**Comment by brett005** [comment]
i think the login page call from api one

**Comment by demianb** [comment]
Hey guys! Initial scratch install documentation for version 4 available on our Wiki page: https://goautodial.org/projects/goautodialce/wiki.

**Comment by hovanessb** [comment]
@demianb Where are the SQL files for the databases mentioned in the link?

**Comment by demianb** [comment]
In the links posted in the HOWTO. 

Snippet:

cd /root/
wget https://downloads2.goautodial.org/files/version4/goautodial.sql
wget https://downloads2.goautodial.org/files/version4/kamailio.sql
wget https://downloads2.goautodial.org/files/version4/osticketdb.sql

**Comment by hovanessb** [comment]
@demianb Great! Thanks so much! I work with Postgresql so I will attempt to get everything working and can give back to the project.

**Comment by brett005** [comment]
thank youuuuuuuuuuuuuuuu

**Comment by brett005** [comment]
i have follow all the sratch the thing that i can not understand is the kamilio why it's not seen registred on asterisk with sip show peers ?

the screen -r loose same process 
on agent login when i click on login dialer i see message login error contact your administrator

**Comment by amitiyer** [comment]
hello,

I have installed Goautodial v4.0 but the web panel is not working i am receiving HTTP Error 500

**Comment by demianb** [comment]
Hey Guys,

Please use our community forum board for discussions, help and etc. This way, the whole community benefits.

**Comment by amitiyer** [comment]
Have created a threadunder Open Discussion, Please have a look at it.

Thanks.

**Comment by demianb** [comment]
@brett005 Let's use our community forum boards for discussion and etc.

**Comment by avilsmeier** [comment]
Hi, just installed v4 using the ISO, everything went smoothly but when i try to login to the admin page with the credentials in the HowTo i get: "Invalid login or password. Please try again."
Help please!

**Comment by jclbc** [comment]
Hi, just installed v4 using the ISO, everything went smoothly but when i try to login to the admin page with the credentials in the HowTo i get: "Invalid login or password. Please try again."

did you solve this problem?
thanks!

**Comment by taceto32** [comment]
Follow guide delete First user and create new one

Il lun 11 mar 2019, 00:20 jclbc <notifications@github.com> ha scritto:

**Comment by jclbc** [comment]
in fresh install, default username and password are not working:
MySQL (mysql -u root -p) http://ServerIPAddress/phpmyadmin/ | root |  
Portal – https://ServerIPAddress/ | goadmin | G0autodial2018

so i don't know how... shell access is ok...

**Comment by jclbc** [comment]
taceto32,
I follow this guide, is there another one?
https://goautodial.org/projects/goautodialce/wiki/Goautodial_Getting_Started_Guidev4
thanks,

**Comment by techsu** [comment]
Unable to run campaign.

**Comment by keffadi** [comment]
Edit the below file to fix the login problem:

Replace xxx.xxx.xxx.xxx - With yur IP Address

#nano /var/www/html/php/goCRMAPISettings.php

```
define ('gourl', 'https://xxx.xxx.xxx.xxx/goAPIv2');
define ('goUser', 'goAPI');
define ('responsetype', 'json');
```


FROM: https://goautodial.org/boards/3/topics/17237

**Comment by martin9621** [comment]
please I install v4 of goautodial I want how access to vicidial page ..thank
