### ISSUE TITLE
Not able login to dialer from agent panel

### ISSUE THREAD

**Issue by zeba121** [goautodial/v4.0#3]
Hello team,

i am not able to login into dialer 

i have checked all permission of campaigns , list , users , groups

but no solution were found

please advise on the same

i am attaching screenshot

![Screenshot_30](https://user-images.githubusercontent.com/46315368/54472859-b9b95000-47f5-11e9-9b86-ebcbcc2974dc.png)

**Comment by taha12us** [comment]
Facing exactly the same issue, this is driving me crazy, 
Followed https://goautodial.org/projects/goautodialce/wiki/Version_4_How_To_Install_Goautodial_From_Scratch_using_CentOS_7X

seems some thing missing in this,
mysql password is vicidialnow.

Goadmin user has also limited rights, unable to fix it, tried to change permissions from phpmyadmin as well, 

![image](https://user-images.githubusercontent.com/22989909/64110472-b1e96a00-cd9b-11e9-9e52-d956ce370393.png)

![image](https://user-images.githubusercontent.com/22989909/64110551-eeb56100-cd9b-11e9-94e2-9e6679ebdb03.png)

**Comment by wittie** [comment]
Hi,

Please update your version using this link https://goautodial.org/projects/goautodialce/wiki/HOWTO_Update_latest_version_via_Github


Thanks

**Comment by Kuntav24** [comment]
Hello, 
Four year later I come back to this issue to know if there is a solution please. I think my installation and all the configuration are ok, but unable to login a campaign
