### ISSUE TITLE
Error in GOagentJS.php

### ISSUE THREAD

**Issue by xxxsidxxx** [goautodial/v4.0#39]
There is error in GOagentJS.php script. I suggest to change goUniqueid in line 6097 to 'goUniqueID'. It will fix the problem with wrong value in the field uniqueid in the table vicidial_agent_log and some problems with "dispo call url" function.

**Comment by mmixx** [comment]
Thanks for this one... It's hard to check on the capitalization of the variables with large quantity of codes :D

**Comment by xxxsidxxx** [comment]
I understand) Thanks a lot!
