### ISSUE TITLE
Leads not getting picked up from hopper

### ISSUE THREAD

**Issue by techsu** [goautodial/v4.0#4]
Hi,
I installed new ISO am not able to run campaign and dialer not dialing leads

**Comment by gudge25** [comment]
same problem

**Comment by absdata** [comment]
Yep. Same issue. Manual dial works. Everything works.

I see 4 leads in list: [Lists](https://yadi.sk/d/BFvHubIWsOTESg)
Agent active and waiting: [Dashboard](https://yadi.sk/i/hK6Zb5P4pEIuKQ)
Campaign is active: 
![image](https://user-images.githubusercontent.com/4988887/81126436-ee312380-8f43-11ea-95d0-6bb813d0b36c.png)

Here is [campaign settings](https://yadi.sk/i/UNnbPfmi7jX5TQ)

Installed from ISO. Version 4 (latest). Updated from this repository.
