### ISSUE TITLE
Support Single Sign On

### ISSUE THREAD

**Issue by blaggacao** [goautodial/v4.0#43]
OpenID-Connect

**Comment by blaggacao** [comment]
Related to #47

**Comment by blaggacao** [comment]
@demianb Are there any plans with respect ot this or to #47 ? Might we help to sponsor such development?

Please just shout out if you feel we should discuss those requirements.

**Comment by demianb** [comment]
Can you tell us more your single sign-on requirements? Our team is currently swamped with dev work. However, if you'll be sponsoring the development of this feature, we can prioritize this.

Please email me at demian @ goautodial.com.

**Comment by blaggacao** [comment]
Perfect @lina2358 will be contacting you in a few days with a more detailed write-up.

**Comment by blaggacao** [comment]
some shared understanding: https://openid.net/connect/

**Comment by blaggacao** [comment]
As for #47 - we can postpone that since it's use case would be to define and synchronize roles (_User Groups_) with an LDAP backend.
