### ISSUE TITLE
Realtime Calls Monitoring Not Popup

### ISSUE THREAD

**Issue by hbondoc** [goautodial/v4.0#52]
I install from scratchGoautodial v4. but the function when on realtime calls Monitoring not popup... is clickable but didn't poupup the page.

**Comment by demianb** [comment]
It's been disabled by default. You can enable it in php/CRMDefaults.php. 

`define ('REALTIME_CALLS_MONITORING', 'n'); //Change to 'y' to enable realtime calls monitoring in Dashboard (not advisable for heavy systems)`
