### ISSUE TITLE
Make php runtime dependencies expilcit

### ISSUE THREAD

**Issue by blaggacao** [goautodial/v4.0#54]
I've searched through the code and the forum, but I was not able to determine the php run time dependencies for either _development_ or _production_ environment.

If somebody might figure that out for me, I might contribute back with implementing a [devshell environment](https://github.com/numtide/devshell) for this project.

**Comment by demianb** [comment]
Hi,

Apologies for the late response. The PHP runtime dependencies are now included in README.md (recently updated).

**Comment by blaggacao** [comment]
Thanks you! Look good!
