### ISSUE TITLE
Missing sip_hangup_cause and empty data in table vicidial_carrier_log

### ISSUE THREAD

**Issue by luandnh** [goautodial/v4.0#56]
Hello team, 
For some reason, the data on the current asterisk's vicidial_carrier_log table is empty even though the system calls and works normally, the table vicidial_dial_log still has the call data as shown below.
![image](https://user-images.githubusercontent.com/49023411/109452277-fa154580-7a81-11eb-8eca-8f571840fe2e.png)
![image](https://user-images.githubusercontent.com/49023411/109452388-3779d300-7a82-11eb-82c5-212f5928775e.png)
I try to compare between goautodial v3 and v4 and see data in table vicidial_carrier_log of v3 still has complete information.
Along with that, the data of the table vicidial_dial_log lost data in the column sip_hangup_cause and reason although v3 is still full.
![image](https://user-images.githubusercontent.com/49023411/109452366-2cbf3e00-7a82-11eb-954b-dae8400fbb16.png)
Can someone on the team help me with this because I need to output the report according to agent call status?

**Comment by demianb** [comment]
Please use our community forums: https://goautodial.org.
