### ISSUE TITLE
Campaign Outbound Autodial and Predictive doesn't work in Goautodial 4

### ISSUE THREAD

**Issue by minhtuan1407** [goautodial/v4.0#57]
Hi GOautodial team,

I am currently moving from GOautodial 3 to GOautodial 4 but I have some problem running Campaign Autodial and Predictive, calls can connect to mobile customer, but it drops right away and there are no media between agent and mobile.

When I compare all files in /etc/asterisk/ there are no differences between our server and GOautodial 4 build from ISO file in https://goautodial.org/boards/20/topics/16826.

This is our asterisk log:

> TLINKVN-26123*CLI>
TLINKVN-26123*CLI>
TLINKVN-26123*CLI>
TLINKVN-26123*CLI>
  == Manager 'sendcron' logged on from 127.0.0.1
  == Manager 'sendcron' logged off from 127.0.0.1
  == Manager 'sendcron' logged on from 127.0.0.1
    -- Called 00965138057@default
    -- Executing [00965138057@default:1] AGI("Local/00965138057@default-0000001c;2", "agi://127.0.0.1:4577/call_log") in new stack
    -- AGI Script Executing Application: (EXEC) Options: (Set(_CAMPCUST=37921977))
    -- <Local/00965138057@default-0000001c;2>AGI Script agi://127.0.0.1:4577/call_log completed, returning 0
    -- Executing [00965138057@default:2] Dial("Local/00965138057@default-0000001c;2", "SIP/0965138057@PITEL01,,tTo") in new stack
  == Using SIP RTP CoS mark 5
    -- Called SIP/0965138057@PITEL01
       > 0x7f41a80125b0 -- Strict RTP learning after remote address set to: 27.71.234.186:22804
    -- SIP/PITEL01-00000015 is making progress passing it to Local/00965138057@default-0000001c;2
    -- Local/00965138057@default-0000001c;1 is making progress
       > 0x7f41a80125b0 -- Strict RTP switching to RTP target address 27.71.234.186:22804 as source
       > 0x7f41a80125b0 -- Strict RTP learning complete - Locking on source address 27.71.234.186:22804
  == Manager 'sendcron' logged on from 127.0.0.1
  == Manager 'sendcron' logged off from 127.0.0.1
TLINKVN-26123*CLI>
TLINKVN-26123*CLI>
TLINKVN-26123*CLI>
TLINKVN-26123*CLI>
TLINKVN-26123*CLI>
TLINKVN-26123*CLI>
    -- SIP/PITEL01-00000015 answered Local/00965138057@default-0000001c;2
    -- Local/00965138057@default-0000001c;1 answered
    -- Channel SIP/PITEL01-00000015 joined 'simple_bridge' basic-bridge <b33910ab-4efd-415b-887a-e9a95dfd52f8>
    -- Executing [138369@default:1] AGI("Local/00965138057@default-0000001c;1", "agi-VDAD_local_optimize.agi,V3011411020000000140") in new stack
    -- Launched AGI Script /usr/share/asterisk/agi-bin/agi-VDAD_local_optimize.agi
    -- Channel Local/00965138057@default-0000001c;2 joined 'simple_bridge' basic-bridge <b33910ab-4efd-415b-887a-e9a95dfd52f8>
  == Manager 'sendcron' logged off from 127.0.0.1
    -- <Local/00965138057@default-0000001c;1>AGI Script agi-VDAD_local_optimize.agi completed, returning 0
    -- Executing [138369@default:2] Wait("Local/00965138057@default-0000001c;1", "2") in new stack
    -- Executing [138369@default:3] Hangup("Local/00965138057@default-0000001c;1", "") in new stack
  == Spawn extension (default, 138369, 3) exited non-zero on 'Local/00965138057@default-0000001c;1'
[Mar  1 14:11:13] WARNING[4875][C-00000031]: func_hangupcause.c:140 hangupcause_read: Unable to find information for channel
    -- Executing [h@default:1] AGI("Local/00965138057@default-0000001c;1", "agi://127.0.0.1:4577/call_log--HVcauses--PRI-----NODEBUG-----16--------------------)") in new stack
    -- <Local/00965138057@default-0000001c;1>AGI Script agi://127.0.0.1:4577/call_log--HVcauses--PRI-----NODEBUG-----16--------------------) completed, returning 0
[Mar  1 14:11:14] WARNING[4875][C-00000031]: func_hangupcause.c:140 hangupcause_read: Unable to find information for channel
    -- Executing [h@default:2] NoOp("Local/00965138057@default-0000001c;1", "") in new stack
    -- Channel Local/00965138057@default-0000001c;2 left 'simple_bridge' basic-bridge <b33910ab-4efd-415b-887a-e9a95dfd52f8>
    -- Channel SIP/PITEL01-00000015 left 'simple_bridge' basic-bridge <b33910ab-4efd-415b-887a-e9a95dfd52f8>
  == Spawn extension (default, 00965138057, 2) exited non-zero on 'Local/00965138057@default-0000001c;2'
    -- Executing [h@default:1] AGI("Local/00965138057@default-0000001c;2", "agi://127.0.0.1:4577/call_log--HVcauses--PRI-----NODEBUG-----16-----ANSWER-----11-----3-----SIP 200 OK)") in new stack
    -- <Local/00965138057@default-0000001c;2>AGI Script agi://127.0.0.1:4577/call_log--HVcauses--PRI-----NODEBUG-----16-----ANSWER-----11-----3-----SIP 200 OK) completed, returning 0
    -- Executing [h@default:2] NoOp("Local/00965138057@default-0000001c;2", "SIP 200 OK") in new stack
TLINKVN-26123*CLI>
TLINKVN-26123*CLI>
TLINKVN-26123*CLI>
TLINKVN-26123*CLI>
TLINKVN-26123*CLI>

00965138057 is my mobile number, and PITEL01 is our SIP Trunk Provider,

This behavior is really weird because Outbound Manual calls is totally fine.

**Comment by egorky** [comment]
Perhaps is what it was happening to me until I accidentally found that it was the AMD malfunctioning. So, give it a try, disable the Answer Machine Detection in the campaign settings and tell us the outcome.

**Comment by minhtuan1407** [comment]
For those who are having similar issue, in my case it is because asterisk is running on user asterisk, the ISO file on which GOautodial team provide is running asterisk on user root. Some of the perl package is missing for user asterisk, but because when I am testing perl files, I use user root, when I try run it with asterisk, there some error missing package, and I fix it from there. I hope it is helpful for you guys.
