### ISSUE TITLE
Kamailio errors: message too short, bad message, bad header field

### ISSUE THREAD

**Issue by jrohde** [goautodial/v4.0#6]
Hi there,

Got everything working (awesome stuff!), but some Kamailio errors are cluttering up the messages log when an agent is logged in (websockets based dailer):

`call /usr/sbin/kamailio[2766]: INFO: <core> [core/parser/parse_fline.c:87]: parse_first_line(): ERROR: parse_first_line: message too short: 4
call /usr/sbin/kamailio[2766]: ERROR: <core> [core/parser/parse_fline.c:257]: parse_first_line(): parse_first_line: bad message (offset: 0)
call /usr/sbin/kamailio[2766]: ERROR: <core> [core/parser/msg_parser.c:671]: parse_msg(): ERROR: parse_msg: message=<PING>
call /usr/sbin/kamailio[2766]: ERROR: <core> [core/parser/msg_parser.c:330]: parse_headers(): bad header field [(null)]
`

It doesn't really seem to influence the functionality, but since it's an "ERROR" it might be good to have it on the issue list.

**Comment by ratssingh** [comment]
I am also troubling with same issue with Kamailio service, Please help how to fix the issue.

Jan 17 18:47:06 vaglxc01.goautodial.com /usr/sbin/kamailio[17676]: ERROR: <core> [core/parser/msg_parser.c:671]: parse_msg(): ERROR: parse_msg: message=<PING>
Jan 17 18:47:06 vaglxc01.goautodial.com /usr/sbin/kamailio[17676]: ERROR: <core> [core/parser/msg_parser.c:330]: parse_headers(): bad header field [(null)]
Jan 17 18:48:06 vaglxc01.goautodial.com /usr/sbin/kamailio[17677]: INFO: <core> [core/parser/parse_fline.c:87]: parse_first_line(): ERROR: parse_first_line: ...short: 4
Jan 17 18:48:06 vaglxc01.goautodial.com /usr/sbin/kamailio[17677]: ERROR: <core> [core/parser/parse_fline.c:257]: parse_first_line(): parse_first_line: bad m...fset: 0)
Jan 17 18:48:06 vaglxc01.goautodial.com /usr/sbin/kamailio[17677]: ERROR: <core> [core/parser/msg_parser.c:671]: parse_msg(): ERROR: parse_msg: message=<PING>
Jan 17 18:48:06 vaglxc01.goautodial.com /usr/sbin/kamailio[17677]: ERROR: <core> [core/parser/msg_parser.c:330]: parse_headers(): bad header field [(null)]
Jan 17 18:49:06 vaglxc01.goautodial.com /usr/sbin/kamailio[17678]: INFO: <core> [core/parser/parse_fline.c:87]: parse_first_line(): ERROR: parse_first_line: ...short: 4
Jan 17 18:49:06 vaglxc01.goautodial.com /usr/sbin/kamailio[17678]: ERROR: <core> [core/parser/parse_fline.c:257]: parse_first_line(): parse_first_line: bad m...fset: 0)
Jan 17 18:49:06 vaglxc01.goautodial.com /usr/sbin/kamailio[17678]: ERROR: <core> [core/parser/msg_parser.c:671]: parse_msg(): ERROR: parse_msg: message=<PING>
Jan 17 18:49:06 vaglxc01.goautodial.com /usr/sbin/kamailio[17678]: ERROR: <core> [core/parser/msg_parser.c:330]: parse_headers(): bad header field [(null)]
Hint: Some lines were ellipsized, use -l to show in full.
[root@vaglxc01 ~]#

**Comment by ratssingh** [comment]
![kamailio service error](https://user-images.githubusercontent.com/46191435/72660205-b2a03700-39f0-11ea-9d15-0153cb045f72.JPG)
