### ISSUE TITLE
install: Failed to insert the initial admin user.

### ISSUE THREAD

**Issue by GSpot1** [goautodial/v4.0#66]
Hi i have problem after final step  to create a admin user i get this error: install: Failed to insert the initial admin user.
Can anyone help is there any permission problems maybe?

**Comment by patrickcmartins** [comment]
Hello, can you send more information about this error?

**Comment by patrickcmartins** [comment]
Can you send more information about this error?

**Comment by Simon55** [comment]
Hi i only get this "Creamy install: Failed to insert the initial admin user" on page when i try to install.

And this in log server 

 Got error 'PHP message: PHP Warning:  require_once(goCRMAPISettings.php): failed to open stream: No such file or directory in /home/xxxx/domains/domain.com/public_html/php/APIHandler.php on line 36PHP message: PHP Fatal error:  require_once(): Failed opening required 'goCRMAPISettings.php' (include_path='.:/usr/local/php73/lib/php') in /home/xxx/domains/domain.com/public_html/php/APIHandler.php on line 36', referer: https://domain.com/install.php

Is probably missing file in  your zip?  goCRMAPISettings.php

**Comment by Simon55** [comment]
I see that was inside this file as example goCRMAPISettings.php-sample i remove it last line  "-sample" but still the same problem.

**Comment by Simon55** [comment]
I try to add rights from 666 to 755 or 777 but still the same problem remain.

**Comment by Simon55** [comment]
@patrickcmartins hi any update how can install different way?

**Comment by patrickcmartins** [comment]
Hello @Simon55 have you tried this?
https://goautodial.org/projects/goautodialce/wiki/HOWTO_Update_latest_version_via_Github

> Hi i only get this "Creamy install: Failed to insert the initial admin user" on page when i try to install.
> 
> And this in log server
> 
> Got error 'PHP message: PHP Warning: require_once(goCRMAPISettings.php): failed to open stream: No such file or directory in /home/xxxx/domains/domain.com/public_html/php/APIHandler.php on line 36PHP message: PHP Fatal error: require_once(): Failed opening required 'goCRMAPISettings.php' (include_path='.:/usr/local/php73/lib/php') in /home/xxx/domains/domain.com/public_html/php/APIHandler.php on line 36', referer: https://domain.com/install.php
> 
> Is probably missing file in your zip? goCRMAPISettings.php

**Comment by Simon55** [comment]
Hi @patrickcmartins i dont use ssh for installation. If is wizard for installation i would like to use that options. Or can be manually import db and settings to config file ? Thank you

**Comment by patrickcmartins** [comment]
Man, you will not be able to handle this error without command line, anything mail me: c.martins13@outlook.com. Ill show you how its done.

**Comment by Simon55** [comment]
Hi @patrickcmartins let us know when that will noo be need todo in the future. Then we will considering to use it. Thank you.

**Comment by demianb** [comment]
Please use our communit forums: https://goautodial.org.
