### ISSUE TITLE
GOautodial login page not working

### ISSUE THREAD

**Issue by HasanHridoy** [goautodial/v4.0#89]
I have installed goautodial 4 from scratch from (https://goautodial.org/projects/goautodialce/wiki/Version_4_How_To_Install_Goautodial_From_Scratch_using_CentOS_7X) but when trying from URL bar it says HTTP error 500.
Please help
![image](https://user-images.githubusercontent.com/44053048/201879496-0e57d33e-7c55-4715-bf94-0ee1e7d08098.png)

**Comment by demianb** [comment]
Have you posted your issues in our community forums (https://goautodial.org)? This way the whole community benefits/helps.
